config/routes.rb
Rails.application.routes.draw do

  get 'books' => 'books#index', as: 'books'
  post 'books' => 'books#create', as: 'create_book'
  #index_pathで/booksが呼び出せるハズ
  #books_pathにしたらなぜか直った
  get 'books/:id' => 'books#show', as: 'book'
  #パス名をshowにしてたらbook_pathが定義されてませんと出たので
  #book_pathがshowに勝手になっているかも？
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'delete_book'
  get '/' => 'homes#top'
  root 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  #各データが空白ではないかチェックする
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    else
    render :index
    #render :アクション名
    end
  end

  def new

  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
     flash[:notice] ="Book was successfully updated."
    redirect_to book_path(@book.id)
   else
   
   render :edit
   end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  #ストロングパラメータ
  #以下、コントローラー内でのみ使用可能
  private
  def book_params
  params.require(:book).permit(:title, :body)
  end
  #bookモデルのタイトル、
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
<div class="error-messages">
  <p class="error-flash-message">
    <%= @book.errors.count %> errors prohibited this book from being saved:
  </p>
  <ul>
    <% @book.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %> 
  </ul>
</div>
<% end %>

<%= form_with model: @book, method: :patch do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Body</p>
  <%= f.text_area :body %>

  <%= f.submit "Update Book" %>
<% end %>

<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<div class="success-flash-message">
  <%= flash[:notice] %>
</div>
<!-- 投稿一覧 目次(th)以下を繰り返し文で表示-->
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
  </tr>
<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td>
      <%= link_to "Show", book_path(book.id) %>
      <%= link_to "Edit", edit_book_path(book.id) %>
      <%= link_to "Destroy", delete_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
    </td>
  </tr>
<% end %>
</table>

<!--  新規投稿　一覧表示とは別のインスタンス変数を定義しておく。-->
<h1>New book</h1>
<!--  エラーメッセージ-->
<% if @book.errors.any? %>
<div class="error-messages">
  <p class="error-flash-message">
    <%= @book.errors.count %> errors prohibited this book from being saved:
  </p>
  <ul>
  <% @book.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
</div>
<% end %>
<%= form_with model: @book, method: :post, local: true do |f| %> 
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Body</p>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class="success-flash-message">
  <%= flash[:notice] %>
</div>

<h3>Title:<%= @book.title %></h3>
<h3>Body:<%=  @book.body %></h3>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ</h1>
<p>
  Bookers では、さまざまな書籍に関するあなたの意見や
</p>
<p>
  印象を共有し交換することができます
</p>
<span><%= link_to "start", books_path %></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>